In [11]:
import pandas as pd

nri_data = pd.read_csv('NRI_Table_CensusTracts.csv')
nri_data = pd.DataFrame(nri_data)
nri_data.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
0,1,T01001020100,Alabama,AL,1,Autauga,County,1,1001,20100,...,19.73452,Relatively Low,2.198943e-07,5.442896e-09,0.000001,55.007178,243.169685,18.941335,Relatively Low,December 2025

### Filter 6 States

In [12]:
nri_data_6states = nri_data[(nri_data['STATE']=='Utah') | (nri_data['STATE']=='California') | 
                    (nri_data['STATE']=='Washington') | (nri_data['STATE']=='Oregon') | 
                    (nri_data['STATE']=='Idaho') | (nri_data['STATE']=='Nevada')]
nri_data_6states.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
4200,4201,T06001400100,California,CA,6,Alameda,County,1,6001,400100,...,19.895738,Relatively Low,7.103804e-08,2.623197e-09,0.0,56.067453,229.35826,18.666063,Relatively Low,December 2025

In [16]:
nri_final_data = nri_data_6states
for i in range (40,414):
    nri_final_data = nri_final_data.drop(nri_data_6states.columns[[i]], axis=1)
for i in range (440, 467):
    nri_final_data = nri_final_data.drop(nri_data_6states.columns[[i]], axis=1)

nri_final_data.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WFIR_EALT,WFIR_EALS,WFIR_EALR,WFIR_ALRB,WFIR_ALRP,WFIR_ALRA,WFIR_ALR_NPCTL,WFIR_RISKV,WFIR_RISKS,WFIR_RISKR
4200,4201,T06001400100,California,CA,6,Alameda,County,1,6001,400100,...,83351.891118,94.186199,Relatively Moderate,0.000056,8.466201e-08,0.0,95.298063,90578.758052,94.00069,Relatively Moderate

In [17]:
nri_final_data.to_csv('CIVE202_Spring2026_GroupINFRA-02-05_Project5_RawData.csv')

### Setup SHP File

In [8]:
import geopandas as gpd
tracts = gpd.read_file('NRI_Shapefile_CensusTracts.shp')

DataSourceError: Unable to open NRI_Shapefile_CensusTracts.shx or NRI_Shapefile_CensusTracts.SHX. Set SHAPE_RESTORE_SHX config option to YES to restore or create it.

In [5]:
include = ['Utah', 'California', 'Washinton', 'Oregon', 'Idaho', 'Nevada']
tracts_6states = tracts[tracts['STATE'].isin(include)]
tracts_6states.to_file("CIVE202_Spring2026_GroupINFRA-02-05_Project5_Shapefile_RawData.shp")

NameError: name 'tracts' is not defined