In [1]:
import pandas as pd

nri_data = pd.read_csv('NRI_Table_CensusTracts.csv')
nri_data = pd.DataFrame(nri_data)
nri_data.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
0,1,T01001020100,Alabama,AL,1,Autauga,County,1,1001,20100,...,19.73452,Relatively Low,2.198943e-07,5.442896e-09,0.000001,55.007178,243.169685,18.941335,Relatively Low,December 2025

In [2]:
nri_data_6states = nri_data[(nri_data['STATE']=='Alaska') | (nri_data['STATE']=='California') | 
                    (nri_data['STATE']=='Washington') | (nri_data['STATE']=='Oregon') | 
                    (nri_data['STATE']=='Hawaii') | (nri_data['STATE']=='Nevada')]
nri_data_6states.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,WNTW_EALS,WNTW_EALR,WNTW_ALRB,WNTW_ALRP,WNTW_ALRA,WNTW_ALR_NPCTL,WNTW_RISKV,WNTW_RISKS,WNTW_RISKR,NRI_VER
1435,1436,T02013000100,Alaska,AK,2,Aleutians East,Borough,13,2013,100,...,83.66283,Relatively High,0.000005,1.750820e-07,0.0,73.629645,21295.135828,92.156536,Relatively High,December 2025

In [11]:
nri_final_data = nri_data_6states
for i in range (40,392):
    nri_final_data = nri_final_data.drop(nri_data_6states.columns[[i]], axis=1)
for i in range (414, 467):
    nri_final_data = nri_final_data.drop(nri_data_6states.columns[[i]], axis=1)

nri_final_data.head(1)

,OID_,NRI_ID,STATE,STATEABBRV,STATEFIPS,COUNTY,COUNTYTYPE,COUNTYFIPS,STCOFIPS,TRACT,...,VLCN_EALPE,VLCN_EALT,VLCN_EALS,VLCN_EALR,VLCN_ALRB,VLCN_ALRP,VLCN_ALR_NPCTL,VLCN_RISKV,VLCN_RISKS,VLCN_RISKR
1435,1436,T02013000100,Alaska,AK,2,Aleutians East,Borough,13,2013,100,...,835375.457659,894979.215776,99.878281,Very High,0.000116,0.000018,96.394066,1.765509e+06,99.935748,Very High

In [12]:
nri_final_data.to_csv('CIVE202_Spring2026_GroupINFRA-02-05_Project5_RawData.csv')